# -*- coding: utf-8 -*-
"""send otp twilio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRVnr54X60gKBsaKwyZjGMERRInY3aOa
"""

!pip install twilio

import os
import random
from twilio.rest import Client

account_sid = "AC4688e7199d8e7c8b412fe609ba6167f0" # akun id twillio
auth_token = "3393672809410fa092f1c609c1e046bd" # auth token twillio
client = Client(account_sid, auth_token)

otp = random.randint(1000,9999)

message = client.messages.create(
         body='tes otp sms, code otp '+str(otp),
         from_='+14154771214', # nomor pengirim, nomor dari twilio
         to='+6287869415384' # nomor tujuan
     )

print(message.sid)